#!/bin/bash

#Get color
source $HOME/snippets/color 

VAR=0 #Container for while loop


#Create array of packages to check
PACKAGES=("tmux" "htop" "nmap" "neofetch" "vim" "figlet" "cmatrix")
ARRAYSIZE=${#PACKAGES[@]} #This variable is created because the length of array would decrease while
			 #through the while loop

#Turned into a function so I can run this after VIM is installed
vim-line-count(){
	#Add line count to VI
	read -p "Would you like to add line count to Vim?[Y/n]" REPLY1
		if [[ "$REPLY1" =~ ^[y-Y]$ ]];
		then
			sudo sed -i ' 50i\set number ' /etc/vim/vimrc
		fi
}


#check if ~/bin is added to env Path
cat /etc/profile | grep ^PATH > /dev/null
EXITSTATUS=$?

if [ $EXITSTATUS != 0 ];
then
	read -p "PATH is not added to profile, would you like to add it? [Y/n]" REPLY2
	if [ "$REPLY2" == "Y" -o "$REPLY2" == "y" ]; #Account for lower and uppercase input
	then
		sudo echo 'PATH=$PATH/home/pi/bin' >> /etc/profile
	
	fi

fi

#Add the Backups
read -p "Would you like to schedule cron to do a backup[Y/n]" REPLY3
	if [ "$REPLY3" == "Y" -o "$REPLY3" == "y" ];
	then
		sudo sed -i "18i\ 1 */3 * * * root  bash /home/pi/bin/backup" /etc/crontab
		sudo sed -i "19i\ 30 */3 * * * root bash /home/pi/bin/remote-backup" /etc/crontab
		echo "All done added backup to /etc/crontab"
		sleep 1
	fi

echo "Checking installed packages: "
#Run through array, and remove laready installed packages
while [ $VAR -lt $ARRAYSIZE  ];
do
	sleep 1
	dpkg -l | grep -i ${PACKAGES[$VAR]} && unset PACKAGES[$VAR]
	let VAR++
	
done

#Install the uninstalled
echo "Installing the packages"
sudo apt install ${PACKAGES[@]}

#Add line count to VIM after it is installed
vim-line-count

echo -e  "${GREEN} Everything is good to go! $RESET"
shutdown -r


exit 0
